language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - ./vendor/bin/parallel-lint ./src/
  - ./vendor/bin/phpmd ./src/ text controversial,design,naming,unusedcode
  - ./vendor/bin/phpcs --standard=phpcs.xml ./src/
  - ./vendor/bin/security-checker security:check
